Support Spring
paion-data/astraios pull request #123
Opened 2024-05-09 10:55 UTC by Doom9527

### Description
Change `mysql-connector-java.version` from 5.1.49 to 8.0.26.

2024-05-09 13:45 UTC, QubitPi reviewed
What is `src/main/resources/META-INF/resources/swagger` for?

2024-05-11 00:48 UTC, QubitPi requested changes
If mysql connector 8.x is used, docker [compose should be updated to use 8.0 too](https://github.com/paion-data/dental-llm-web-app/pull/44/files#diff-3d9479394597b1c295eb12ae52847bdebcd024797fa93d2ab34a41362cbe758fR20)

2024-05-11 19:42 UTC, Doom9527 commented
Mentioned before the problem of `ResourceConfigITSpec` has been solved, but `DockerComposeITSpec` has a problem, I have not seen what happened, may be caused by the former repair

2024-05-12 13:53 UTC, QubitPi requested changes

2024-05-12 13:53 UTC, QubitPi commented on Dockerfile
The `maintainer` and `maintainer-email` can be changed to @Doom9527 's identity

2024-05-12 13:53 UTC, QubitPi commented on Dockerfile
> +    PATH=$JAVA_HOME/bin:$PATH
Why would `PATH=$JAVA_HOME/bin:$PATH` become **necessary**?

2024-05-12 13:53 UTC, QubitPi commented on Dockerfile
> +ENTRYPOINT ["/usr/lib/jvm/java-17-openjdk-amd64/bin/java", "-jar", "/tmp/app.jar"]
If `JAVA_HOME` is set correctly, we can simply put `java` instead of `/usr/lib/jvm/java-17-openjdk-amd64/bin/java`, which is hard to read

2024-05-12 14:21 UTC, QubitPi requested changes

2024-05-12 14:21 UTC, QubitPi commented on docker-compose.yml
> +      - DB_URL=jdbc:mysql://db:3306/elide?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
Isn't 3306 be picked up automatically?

What requires us to use `allowPublicKeyRetrieval`?

2024-05-12 14:21 UTC, QubitPi commented on docker-compose.yml
> +      - "3306:3307"
Are MySQL running at 3307 in container??

2024-05-12 14:21 UTC, QubitPi commented on docker-compose.yml
> +      test: mysqladmin ping -h localhost -u root -proot -P3307
Is something wrong with 3306? **We can assume the host always have 3306 open**. The more default we are using, the easier for us to maintain a software

2024-05-12 14:30 UTC, QubitPi requested changes

2024-05-12 14:30 UTC, QubitPi commented on logback/astraios.2024-05-09.log
`logback` should not be pushed. We should add it to .gitignore

2024-05-12 14:30 UTC, QubitPi commented on logback/astraios.2024-05-10.log
delete

2024-05-12 14:30 UTC, QubitPi commented on logback/astraios.log
delete

2024-05-12 14:30 UTC, QubitPi commented on pom.xml
> +        <!-- Use Jetty -->
We no longer use Jetty, right?

2024-05-12 14:30 UTC, Doom9527 commented on Dockerfile
> +    PATH=$JAVA_HOME/bin:$PATH
This simplifies the startup commands.

2024-05-12 14:31 UTC, Doom9527 commented on Dockerfile
> +ENTRYPOINT ["/usr/lib/jvm/java-17-openjdk-amd64/bin/java", "-jar", "/tmp/app.jar"]
It's true. I've changed it to `ENTRYPOINT ["java", "-jar", "/tmp/app.jar"]`

2024-05-12 15:06 UTC, Doom9527 commented on docker-compose.yml
> +      - DB_URL=jdbc:mysql://db:3306/elide?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
They are really not necessary and I will remove them.

2024-05-12 15:11 UTC, Doom9527 commented on docker-compose.yml
> +      - "3306:3307"
I'll change them back to `3306:3306`

2024-05-12 15:11 UTC, Doom9527 commented on docker-compose.yml
> +      test: mysqladmin ping -h localhost -u root -proot -P3307
I'll remove them.

2024-05-12 15:13 UTC, QubitPi requested changes

2024-05-12 15:13 UTC, QubitPi commented on src/main/java/com/paiondata/astraios/keyConfig/ApplicationConfig.java
> +    @DefaultValue("com.paiondata.astraios.models")
The thing inside `""` is confidential and cannot be exposed publicly. Please remove it and rebase commits to hide it from git history

2024-05-12 15:18 UTC, QubitPi requested changes

2024-05-12 15:18 UTC, QubitPi commented on src/main/java/com/paiondata/astraios/config/SecurityConfiguration.java
> + * Disables security for testing.
Elide did a horrible job on this. We should not have any test-only class in production code like this. Please remove `SecurityConfiguration`

2024-05-12 15:46 UTC, Doom9527 commented on pom.xml
> +        <!-- Use Jetty -->
This dependency uses Jetty as the built-in HTTP server.
Remove the built-in Tomcat on line 128.

2024-05-12 23:08 UTC, QubitPi requested changes

2024-05-12 23:10 UTC, QubitPi requested changes

2024-05-12 23:10 UTC, QubitPi commented on src/main/java/com/paiondata/astraios/OpenApiConfiguration.java
> +public class OpenApiConfiguration {
We know that our UI will query WS by GraphQL, not JSON API. `OpenApiConfiguration` is there specifically for booting up JSON API Swagger. We should remove it.

2024-05-12 23:25 UTC, QubitPi requested changes
**The entire `src/main/resources/analytics/`, `src/main/resources/db/`, `src/main/resources/META-INF` can be deleted**

2024-05-12 23:25 UTC, QubitPi commented on .gitignore
> +logback/
new line <img src="https://github.com/QubitPi/QubitPi/blob/master/code-reviews/%E9%9C%8D%E9%9C%8D/%E9%9C%8D%E9%9C%8D3.png?raw=true" width="60px" />

2024-05-12 23:25 UTC, QubitPi commented on Dockerfile
> +    PATH=$JAVA_HOME/bin:$PATH
What would command look like without it?

2024-05-12 23:25 UTC, QubitPi commented on docker-compose.yml
> +      - DB_URL=jdbc:mysql://db:3306/elide?serverTimezone=UTC
Is 3306 still need to be explicitly specified?

2024-05-12 23:25 UTC, QubitPi commented on src/main/java/com/paiondata/astraios/AppRuntimeHints.java
> +public class AppRuntimeHints implements RuntimeHintsRegistrar {
The astraios APP at this moment will looks super simple. [This is a very good sign because all software starts simple](https://en.wikipedia.org/wiki/John_Gall_(author)#Gall's_law) and it will for sure become big and complicated

[`AppRuntimeHints` is an overkill](https://medium.com/@nanayakkaraoffice/spring-boot-3-graalvm-hint-api-28e0e169d227) for now. We don't need it. Make sure to remove unnecessary dependencies from POM as well

2024-05-12 23:30 UTC, QubitPi commented on pom.xml
> +            <artifactId>micrometer-tracing-bridge-brave</artifactId>
[I think removing `RuntimeHintsRegistra` makes this deletable](https://github.com/paion-data/astraios/pull/123#discussion_r1597738304)

2024-05-12 23:30 UTC, QubitPi commented on pom.xml
> +            <artifactId>artemis-jakarta-server</artifactId>
[I think removing `RuntimeHintsRegistra` makes this deletable](https://github.com/paion-data/astraios/pull/123#discussion_r1597738304)

2024-05-13 02:53 UTC, Doom9527 commented on Dockerfile
> +    PATH=$JAVA_HOME/bin:$PATH
Here's a mistake I made. The command would look like `ENTRYPOINT ["java", "-jar", "/tmp/app.jar"]` with it, But I used `ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64 \
    PATH=$JAVA_HOME/bin:$PATH` here.

2024-05-13 02:55 UTC, Doom9527 commented on src/main/java/com/paiondata/astraios/filters/MyCorsFilter.java
> +public class MyCorsFilter implements Filter {
Ok, I'll remove it.

2024-05-13 05:02 UTC, Doom9527 commented on src/main/java/com/paiondata/astraios/AppRuntimeHints.java
> +public class AppRuntimeHints implements RuntimeHintsRegistrar {
I understand. I will remove them.

2024-05-14 04:49 UTC, QubitPi requested changes

2024-05-14 04:49 UTC, QubitPi commented on Dockerfile
> +    PATH=$JAVA_HOME/bin:$PATH
Can we delete `PATH=$JAVA_HOME/bin:$PATH`? It seems unnecessary

2024-05-14 04:49 UTC, QubitPi commented on src/main/resources/application.yaml
In theory, `ElideConfiguration` and this file does essentially the same thing. I am expecting one of them is removed. Am I wrong?

2024-05-14 04:53 UTC, QubitPi requested changes

2024-05-14 04:53 UTC, QubitPi commented on src/main/resources/logback-spring.xml
> +
Remove the extra empty line

2024-05-14 04:53 UTC, QubitPi commented on src/main/resources/logback-spring.xml
> +    <logger name="com.yahoo.elide.datastores.aggregation.core.Slf4jQueryLogger" level="DEBUG" />
We don't use [aggregation](https://elide.io/pages/guide/v5/04-analytics.html) feature. So it can be removed

2024-05-14 04:53 UTC, QubitPi commented on src/main/resources/logback-spring.xml
> +    <logger name="io.swagger.v3.core.util.ReferenceTypeUtils" level="OFF" />
We don't use swagger

2024-05-14 04:53 UTC, QubitPi commented on src/main/resources/logback-spring.xml
> +    <logger name="com.yahoo.elide.graphql.subscriptions" level="DEBUG" />
We don't use [subscription](https://elide.io/pages/guide/v6/11.1-subscriptions.html) feature, so this line can be removed

2024-05-14 04:57 UTC, QubitPi requested changes

2024-05-14 04:57 UTC, QubitPi commented on src/test/groovy/com/paiondata/astraios/config/SpringbootJarITSpec.groovy
> +        Thread.sleep(5000)
[This is makes a test nondeterministic, which is a sub-optimal practice](https://martinfowler.com/articles/nonDeterminism.html#WhyNon-deterministicTestsAreAProblem)

In fact, [Spring has it's own IT test paradigm](https://www.baeldung.com/spring-boot-testing#integration-testing-with-springboottest)

2024-05-14 05:02 UTC, QubitPi requested changes

2024-05-14 05:02 UTC, QubitPi commented on src/test/groovy/com/paiondata/astraios/config/DockerComposeITSpec.groovy
> +            .withEnv("DB_DIALECT", "org.hibernate.dialect.MySQLDialect")
This looks like a smell. Aren't we picking up the [default values from `docker-compose.yml`](https://github.com/paion-data/astraios/blob/d210af8f329fc04c6ab5e366021a6a0bb7c12fd1/docker-compose.yml#L9-L14)?

2024-05-14 05:02 UTC, QubitPi commented on src/test/groovy/com/paiondata/astraios/config/AbstractITSpec.groovy
> +import static com.yahoo.elide.test.jsonapi.JsonApiDSL.*
Star import is a big red flag. What is our checkstyle doing??? <img src="https://github.com/QubitPi/QubitPi/blob/master/code-reviews/%E9%9C%8D%E9%9C%8D/%E9%9C%8D%E9%9C%8D1.png?raw=true" width="60px" />

2024-05-14 05:05 UTC, QubitPi commented on src/main/java/com/paiondata/astraios/models/Book.java
If `Book` is used in test only, it should be moved to somerwhere under `test` directory

2024-05-14 05:06 UTC, QubitPi commented on src/main/java/com/paiondata/astraios/keyConfig/JpaDatastoreConfig.java
> +    @DefaultValue("create")
**This is very dangerous. Imagine every deployment into production erases all our customer's data...**

<img src="https://github.com/QubitPi/QubitPi/blob/master/code-reviews/%E9%9C%8D%E9%9C%8D/%E9%9C%8D%E9%9C%8D1.png?raw=true" />

2024-05-14 05:22 UTC, QubitPi requested changes

2024-05-14 05:22 UTC, QubitPi commented on src/main/java/com/paiondata/astraios/keyConfig/JpaDatastoreConfig.java
> +    @DefaultValue("org.hibernate.dialect.H2Dialect")
It's not a good idea to put test value here. We should explicitly leave it unset to enforce all explicit configuration

2024-05-14 05:22 UTC, QubitPi commented on src/main/java/com/paiondata/astraios/keyConfig/JpaDatastoreConfig.java
> +    @DefaultValue("org.h2.Driver")
It's not a good idea to put test value here. We should explicitly leave it unset to enforce all explicit configuration

2024-05-14 05:22 UTC, QubitPi commented on src/main/java/com/paiondata/astraios/keyConfig/JpaDatastoreConfig.java
> +    @DefaultValue("jdbc:h2:mem:elide;DB_CLOSE_DELAY=-1")
It's not a good idea to put test value here. We should explicitly leave it unset to enforce all explicit configuration

2024-05-14 05:22 UTC, QubitPi commented on src/main/java/com/paiondata/astraios/keyConfig/JpaDatastoreConfig.java
> +    @DefaultValue("")
It's not a good idea to put test value here. We should explicitly leave it unset to enforce all explicit configuration

And an empty password is never a good idea

2024-05-14 05:22 UTC, QubitPi commented on src/main/java/com/paiondata/astraios/keyConfig/JpaDatastoreConfig.java
> +    @DefaultValue("sa")
It's not a good idea to put test value here. We should explicitly leave it unset to enforce all explicit configuration

2024-05-14 05:22 UTC, QubitPi commented on src/main/java/com/paiondata/astraios/keyConfig/ApplicationConfig.java
> +    @DefaultValue("com.paiondata.astraios.models")
It's not a good idea to put test value here. We should explicitly leave it unset to enforce all explicit configuration

2024-05-14 05:22 UTC, QubitPi commented on src/main/java/com/paiondata/astraios/keyConfig/ApplicationConfig.java
> +package com.paiondata.astraios.keyConfig;
What makes `keyConfig` a better name? `key` is a bit ambiguous which makes code little hard to read

2024-05-14 05:22 UTC, QubitPi commented on src/main/java/com/paiondata/astraios/config/SecurityConfiguration.java
> +    CorsConfigurationSource corsConfigurationSource(final SecurityConfigProperties properties) {
We should make this bean an optional. Because in our architecture, we might not need this

2024-05-14 05:23 UTC, QubitPi commented on src/main/java/com/paiondata/astraios/config/SecurityConfigProperties.java
> +@ConfigurationProperties(prefix = "app.security")
We should make this bean an optional. Because in our architecture, we might not need this

2024-05-14 05:26 UTC, QubitPi requested changes
Much better 👍🏻 ...and can be even much better

2024-05-14 05:50 UTC, Doom9527 commented on src/test/groovy/com/paiondata/astraios/config/AbstractITSpec.groovy
> +import static com.yahoo.elide.test.jsonapi.JsonApiDSL.*
This is a mistake I made, I used the optimized import function of IDEA, I will correct it. But checkstyle doesn't actually check groovy files.

2024-05-14 05:56 UTC, Doom9527 commented on src/main/resources/application.yaml
`PATH=$JAVA_HOME/bin:$PATH` can be deleted, and I will delete it.

2024-05-14 05:59 UTC, Doom9527 commented on src/main/java/com/paiondata/astraios/keyConfig/JpaDatastoreConfig.java
> +    @DefaultValue("create")
This is my problem, I changed it to `create` for the convenience of testing, but I did not change it back, I will correct it.

2024-05-14 06:01 UTC, QubitPi commented on src/test/groovy/com/paiondata/astraios/config/AbstractITSpec.groovy
> +import static com.yahoo.elide.test.jsonapi.JsonApiDSL.*
I see. Just to make sure. Did you take advantage of https://github.com/paion-data/astraios/blob/master/Astraios-Project-intellij-code-style.xml ?

2024-05-14 06:03 UTC, Doom9527 commented on src/main/java/com/paiondata/astraios/keyConfig/JpaDatastoreConfig.java
> +    @DefaultValue("org.hibernate.dialect.H2Dialect")
I'll remove them all, but I think setting them as default values for the h2 database not only makes it easier to test, but also makes it easier for others to use `astraiois`. By default you don't have to configure the mysql database, which is what `elide-spring-boot-example` does.

2024-05-14 06:08 UTC, Doom9527 commented on src/main/java/com/paiondata/astraios/keyConfig/ApplicationConfig.java
> +package com.paiondata.astraios.keyConfig;
I rename it to `settings`.

2024-05-14 08:51 UTC, Doom9527 commented on src/main/java/com/paiondata/astraios/config/SecurityConfigProperties.java
> +@ConfigurationProperties(prefix = "app.security")
When `app.security.origin` is not defined, the `SecurityConfigProperties` can accept the default values. This is already done in `SecurityConfigProperties` by setting the default value `origin = "*"`

2024-05-14 09:50 UTC, Doom9527 commented on src/test/groovy/com/paiondata/astraios/config/AbstractITSpec.groovy
> +import static com.yahoo.elide.test.jsonapi.JsonApiDSL.*
yes

2024-05-16 07:25 UTC, QubitPi requested changes

2024-05-16 07:25 UTC, QubitPi commented on pom.xml
> +            <artifactId>spring-boot-starter-artemis</artifactId>
I believe we don't need ActiveMQ Artemis, do we?

2024-05-16 07:25 UTC, QubitPi commented on quickstart.sh
> +MODEL_PACKAGE_NAME=com.paiondata.dental.llm.astraios.models docker compose up --build --force-recreate
We should use the open source version model, instead of this internal one.

2024-05-16 07:34 UTC, QubitPi commented on src/main/java/com/paiondata/astraios/keyConfig/JpaDatastoreConfig.java
> +    @DefaultValue("org.hibernate.dialect.H2Dialect")
You are quite right on being user-friendly and following `elide-spring-boot-example`. Given that astraios is a production-ready app instead of an `example` toy app, what we are actually trying to achieve is **we want absolute zero possibility of any production config being left unattended**, because any test config slipped into production is a bug. The best way then is to throw an error that stops our service from running against our business users by initially setting it to `null`

2024-05-16 07:35 UTC, QubitPi commented on src/main/resources/application.yaml
I fully agree

2024-05-16 07:42 UTC, QubitPi commented on src/main/java/com/paiondata/astraios/config/SecurityConfiguration.java
> +    CorsConfigurationSource corsConfigurationSource(final SecurityConfigProperties properties) {
I'm not sure if I'm following. I'll chat with you on Slack

2024-05-16 07:43 UTC, Doom9527 commented on pom.xml
> +            <artifactId>lombok</artifactId>
ok. I will remove it.

2024-05-16 07:44 UTC, QubitPi requested changes

2024-05-16 07:44 UTC, QubitPi commented on src/main/java/com/paiondata/astraios/settings/JpaDatastoreConfig.java
> +     * The SQL DB driver class name, such as "org.h2.Driver".
How about `The SQL DB driver class name, such as "org.h2.Driver" or "com.mysql.jdbc.Driver".`?

2024-05-16 07:47 UTC, Doom9527 commented on src/main/java/com/paiondata/astraios/keyConfig/JpaDatastoreConfig.java
> +    @DefaultValue("org.hibernate.dialect.H2Dialect")
Got it.

2024-05-16 07:51 UTC, QubitPi commented on quickstart.sh
> +MODEL_PACKAGE_NAME=com.paiondata.dental.llm.astraios.models docker compose up --build --force-recreate
Have you used [squash](https://www.git-tower.com/learn/git/faq/git-squash) before? We need it now to remove this piece of confidential code from git history

2024-05-16 07:51 UTC, Doom9527 commented on src/main/java/com/paiondata/astraios/settings/JpaDatastoreConfig.java
> +     * The SQL DB driver class name, such as "org.h2.Driver".
ok, I will rename it to `com.mysql.cj.jdbc.Driver`

2024-05-16 08:21 UTC, Doom9527 commented on pom.xml
> +            <artifactId>spring-boot-starter-artemis</artifactId>
yes

2024-05-16 08:22 UTC, Doom9527 commented on pom.xml
> +                <artifactId>native-maven-plugin</artifactId>
It is not necessary. I'll remove it.

2024-05-16 11:07 UTC, Doom9527 commented on src/main/java/com/paiondata/astraios/config/SecurityConfigProperties.java
> +@ConfigurationProperties(prefix = "app.security")
add `@ConditionalOnProperty(prefix = "app.security", name = "cors.enabled", havingValue = "true", matchIfMissing = false)` to make it optional.

2024-05-16 11:07 UTC, Doom9527 commented on src/main/java/com/paiondata/astraios/config/SecurityConfiguration.java
> +    CorsConfigurationSource corsConfigurationSource(final SecurityConfigProperties properties) {
add `@ConditionalOnProperty(prefix = "app.security", name = "cors.enabled", havingValue = "true", matchIfMissing = false)` to make it optional.

2024-05-16 12:00 UTC, QubitPi reviewed
Almost done. Just minor tweaks 😉

2024-05-16 12:46 UTC, QubitPi approved these changes
👍🏻

2024-05-16 12:49 UTC, merged