Add documentation translation
paion-data/astraios pull request #88
Opened 2023-12-28 03:20 UTC by TristeOak

Add Chinese translation of configuration.md and intro.mdx

Changelog
---------

### Added

### Changed

### Deprecated

### Removed

### Fixed

### Security

Checklist
---------

- [ ] Test
- [ ] Self-review
- [ ] Documentation

2023-12-28 04:04 UTC, QubitPi commented
Thanks for contributing, @TristeOak .

Meanwhile, please rebase your fork to fix the CI/CD error above (We've patched our `master` branch in order to fix that error). When that get's done, I'll take a look at this today.

If you are interested in joining us for an internship, please ping us on zhipin.com and mention this PR

If this PR gets merged, we will add you to our contributor list displayed on our README

Thanks again for contributing.

2023-12-28 10:27 UTC, TristeOak commented
Hi Jiaqi,

My name is Ziyao Jin. I'm very interested in open source projects but I'm just a beginner. I'm currently studying at ANU. Since the summer break in Australia is relatively long, I really want to do an internship to further study software engineering. 

Please let me know if my translation is accurate, as I'm still somewhat unclear about some concepts. I'm eager to contribute more to open source projects and I will continue to look for issues that I can solve on GitHub. 

I‘ve rebased the fork and I will contact you on Zhipin after you review my work to check if it meets the standards.

Sincerely,
Ziyao Jin

2023-12-28 12:31 UTC, QubitPi requested changes
Overall, pretty high-quality translation 👍🏻 Please see the review comments below.

2023-12-28 12:31 UTC, QubitPi commented on docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/configuration.md
> +| OAUTH_PROPERTIES               | 上述提到的 `src/main/resources/oauth.properties` 文件的内容                                                                                                          | 请参阅上述的
`#security` -> `##oauth-2`

2023-12-28 12:31 UTC, QubitPi commented on docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/configuration.md
> +| JPADATASTORE_PROPERTIES        | 上述提到的 `src/main/resources/jpadatastore.properties` 文件的内容                                                                                                   | 请参阅上述的
`#jpa-datastore` -> `#elide-jpa-datastore`

2023-12-28 12:31 UTC, QubitPi commented on docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/configuration.md
> +| DATA_MODELS_PRIVATE_REPO_TOKEN | 用于 Elide 数据模型存储库的 GitHub Fine-grained token，至少具有“对代码和元数据的读取权限”                                                | [创建 fine-grained personal access token](https://docs
`用于 Elide 数据模型存储库的 GitHub Fine-grained token` -> `用于访问 Elide Data Model 代码仓库的 GitHub PAT token`

2023-12-28 12:31 UTC, QubitPi commented on docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/configuration.md
> +| DATA_MODELS_PRIVATE_REPO_ORG   | Elide 数据模型的 GitHub 存储库的组织或用户名称                                                                                                                         | 对[这个例子](htt
- `Elide Data Model 代码仓库`
- `组织` -> `GitHub 组织`

2023-12-28 12:31 UTC, QubitPi commented on docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/configuration.md
> +| DATA_MODELS_PRIVATE_REPO_NAME  | Elide 数据模型的 GitHub 存储库的名称                                                                                                                                  | 对[这个例子]
`Elide Data Model 代码仓库`

2023-12-28 12:31 UTC, QubitPi commented on docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/configuration.md
> +| AWS_ACCESS_KEY_ID              | 与[配置 AWS CLI 的环境变量](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html)中提到的完全相同的 `AWS_ACCESS_KEY_ID`     | [如何为 Amazon Keyspaces 创建和配置 AWS
`AWS 凭据` -> `AWS 访问密钥 ID`

2023-12-28 12:31 UTC, QubitPi commented on docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/configuration.md
> +| AWS_SECRET_ACCESS_KEY          | 与[配置 AWS CLI 的环境变量](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html)中提到的完全相同的 `AWS_SECRET_ACCESS_KEY` | [如何为 Amazon Keyspaces 创建和配置 AWS
`AWS 凭据` -> `AWS 访问密钥 ID`

2023-12-28 12:31 UTC, QubitPi commented on docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/configuration.md
> +| AWS_REGION                     | 与[配置 AWS CLI 的环境变量](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html)中提到的完全相同的 `AWS_REGION`            | [如何为 Amazon Keyspaces 创建和配置 AWS
`AWS 凭据` -> `AWS 访问密钥 ID`

2023-12-28 12:31 UTC, QubitPi commented on docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/configuration.md
> +| APPLICATION_PROPERTIES         | 上述提到的 `src/main/resources/application.properties` 文件的内容                                                                                                    | 请参阅上述的
`#core-properties` -> `#主要配置`

2023-12-28 12:31 UTC, QubitPi commented on docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/intro.mdx
> +-------------------
```
需要搭建一个 API ？
----------------
```

2023-12-28 12:31 UTC, QubitPi commented on docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/intro.mdx
> +--------------------------
```
将仓库模版实例化
--------------
```

2023-12-28 12:31 UTC, QubitPi commented on docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/intro.mdx
> +1. 使用 `git clone https://github.com/paion-data/astraios.git` 克隆存储库，或者
`存储库` -> `代码仓库`

2023-12-28 12:31 UTC, QubitPi commented on docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/intro.mdx
> +---------------
```
创建数据模型
----------
```

2023-12-28 12:31 UTC, QubitPi commented on docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/intro.mdx
> +@Table(name = "Book")
`Book` -> `book`

[JPA entity is better off using non-caped table name](https://dev.mysql.com/doc/refman/8.0/en/identifier-case-sensitivity.html#:~:text=Table%20names%20are%20stored%20in,database%20names%20and%20table%20aliases.). I just noticed this. Not your fault.

2023-12-28 12:31 UTC, QubitPi commented on docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/intro.mdx
> +-------------------
```
加载数据模型
----------
```

2023-12-28 12:31 UTC, QubitPi commented on docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/intro.mdx
> +-------
```
运行
----
```

2023-12-28 12:31 UTC, QubitPi commented on docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/intro.mdx
> +```
```bash
cd my-webservice
mvn clean package
MODEL_PACKAGE_NAME=com.qubitpi.ws.jersey.template.models docker compose up --build --force-recreate

:::info

`com.qubitpi.ws.jersey.template.models` 是之前提到的[数据模型包][jersey-webservice-template-jpa-data-models]名称

:::
```

This is a documentation bug. I've corrected English version of it. Please update translation like this. Thanks

2023-12-28 12:31 UTC, QubitPi commented on docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/intro.mdx
> +------------
```
写入数据
--------
```

2023-12-28 12:31 UTC, QubitPi commented on docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/intro.mdx
> +当我们运行这个 cURL 调用时，应该会看到返回很多 JSON，这就是我们新插入的对象！
`插入的对象` -> `创建的数据对象`

2023-12-28 12:31 UTC, QubitPi commented on docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/intro.mdx
> +    只需打开最喜欢的浏览器并访问 **http://localhost:8080/v1/data/book**
`只需打开最喜欢的浏览器并访问` -> `只需打开任意浏览器并访问`

2023-12-28 12:31 UTC, QubitPi commented on docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/intro.mdx
> +扩展来查看结果以获得更好的查看体验
`以获得更好的查看体验` -> `，数据内容更加易读`

2023-12-28 12:31 UTC, QubitPi commented on docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/intro.mdx
> +### 修改数据
更新数据

2023-12-28 12:31 UTC, QubitPi commented on docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/intro.mdx
> +请注意，我们创建它时并没有设置新书记录的任何属性。更新数据来帮助用户与添加新数据一样简单。
`更新数据来帮助用户与添加新数据一样简单` -> `用户更新数据和添加新数据一样简单`

2023-12-28 12:31 UTC, QubitPi commented on docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/intro.mdx
> +使用以下 cURL 调用更新我们的模型。
`我们的模型` -> `我们的数据`

2023-12-29 02:15 UTC, TristeOak commented
Thank you for the review comments! I have corrected the translation and also looked into the shared links.

2023-12-29 03:47 UTC, QubitPi commented
Awesome. I'll take a look today. Thanks

2023-12-29 06:18 UTC, merged

2023-12-29 06:38 UTC, QubitPi commented
Merged. Thank you, @TristeOak 

If you are interested in more translation, I'm updating the https://github.com/paion-data/astraios/issues/55 in a moment to include more pages to translate

If you are instead interested in Webservice development using Java and [Groovy Spock](https://spockframework.org/), I'm opening up more issues and you can come back in a few days to see if any issue interests you

2023-12-29 07:13 UTC, TristeOak commented
Thank you for merging my PR and for the information, @QubitPi 

I'm very interested in doing more translations and will continue to work on the documents according to #55. 
 
Regarding webservice development, I'm not certain of my capabilities in that area, but I'm willing to try and learn more about the project. Then, I could start with some basic tasks and gradually take on more complex issues.